settings = struct( ...
    "serial", struct( ...
        "port", "COM6", ...
        "baudrate", 4800, ...
        "timeout", 1, ...
        "terminator", "CR"), ...
    "telemetryFig", figure('Name', 'Telemetry', 'NumberTitle', 'off'));