function [settings] = loadSettings()

realterm_settings = struct( ...
    "Caption", "RealTerm Telemetry Istance", ...
    "LinefeedIsNewline", 1, ...
    "HalfDuplex", 1, ...
    "DisplayAs", 9, ...
    "Port", "6", ...
    "Baud", 4800, ...
    "AddCannedSendString", NaN, ...
    "CharDelay", 10, ...
    "LineDelay", 100);

realterm_settings.AddCannedSendString = { ...
    '$PLCJ,6AFE,6E00,AA,8373,5353\n' ...
    '$PLCJE8BC8,69A8,2D00,2165,6F,\n' ...
    '$WIXDR,C,027.0,C,,*57\n' ...
    '$IIMWV,180.0,R,000.3,N,A*37\n' ...
    };

telemetry_settings = struct( ...
    "parent_figure", figure('Name', 'Telemetry', 'NumberTitle', 'off'), ...
    "pooling_delay", 1);

settings = struct( ...
    "realterm", realterm_settings, ...
    "telemetry", telemetry_settings);

end